Update to Yocto 2.2 (morty)
siemens/meta-iot2000 pull request #23
Opened 2017-05-02 16:49 UTC by jan-kiszka

Long cooking, this is now the official pull request for that major update.

Our workaround for running Arduino binaries for the Galileo Gen2 unmodified on the IOT2000 broke as upstream removed the dusty uclibc support. So this adopts the recipes from 2.1 until we have our own Arduino toolchain.

Along with the base layer update, almost all other dependencies are brought to their latest and/or working morty states.

2017-05-03 08:43 UTC, stormc requested changes

2017-05-03 08:43 UTC, stormc commented on meta-iot2000-example/README.md
> +in ()[../meta-iot2000-bsp/README.md].
This markdown link is broken

2017-05-03 08:43 UTC, stormc commented on meta-iot2000-bsp/README.md
> +This uses Yocto 2.2 (Morty) with the 4.8 Linux kernel provided by Yocto and
Hm, you're selecting the 4.4 kernel as preferred in commit "bsp: Select the 4.4 yocto kernel" while saying that 4.8 of Morty is used here?

2017-05-03 19:13 UTC, jan-kiszka commented
@stormc thanks, both fixed.

2017-05-04 09:28 UTC, stormc approved these changes

2017-05-18 16:11 UTC, merged