example: remove extraneous code block fence in README.md
siemens/meta-iot2000 pull request #26
Opened 2017-05-14 17:05 UTC by stormc

Signed-off-by: Christian Storm <christian.storm@siemens.com>

2017-05-14 17:12 UTC, jan-kiszka requested changes
All 3 or even 4 (blank) lines should go, see f2f389e8fb115e42319c7d323a9ffa2e304dd880.

2017-05-14 18:30 UTC, stormc commented on meta-iot2000-example/README.md
>  ()[../meta-iot2000-bsp/README.md]. The changes to conf/local.conf are the same.
Note: this broken link is fixed [here](https://github.com/siemens/meta-iot2000/pull/23/files#diff-83b9da2db5f8438a48c811daa6692f5fR103).

2017-05-14 19:18 UTC, jan-kiszka commented on meta-iot2000-example/README.md
>  ()[../meta-iot2000-bsp/README.md]. The changes to conf/local.conf are the same.
Now you probably want to adjust $subject as well.

2017-05-14 20:35 UTC, stormc commented on meta-iot2000-example/README.md
>  ()[../meta-iot2000-bsp/README.md]. The changes to conf/local.conf are the same.
Jap, right, done.

2017-05-15 03:47 UTC, jan-kiszka approved these changes

2017-05-18 16:21 UTC, merged