Jan/staging
siemens/meta-iot2000 pull request #30
Opened 2017-05-26 14:28 UTC by jan-kiszka

* rework of the switchserialmode tool
* removal of the unused setledcolor script
* removal of Java build-dependency (yeah!)
* updated Yocto kernel to 4.4.60, including
    * fix for rs485 state reading
    * workaround for broken GPIO expander interrupts

2017-05-26 15:29 UTC, stormc reviewed
Minor changes.

2017-05-26 15:29 UTC, stormc commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +	       "DEVICE\t\tThe device you for which you want to switch the mode.\n"
Hm, while at it, you may also correct the grammar: "[...] you for which you [...]"

2017-05-26 15:29 UTC, stormc commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +		return 1;
Just nitpicking but an argument error should have a different exit code than a real error.

2017-05-26 15:29 UTC, stormc commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +				return 1;
This can be considered an argument error as well and consequently may have a different exit code.

2017-05-26 15:29 UTC, stormc commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +			return 1;
Same same.

2017-05-26 15:29 UTC, stormc commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +	if (!strcmp(argv[1], "--help")) {
I think now it's time to use, e.g., `getopt`? :)

2017-05-26 15:42 UTC, jan-kiszka commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +		return 1;
Is that a convention? Is there one for the value as well?

2017-05-26 15:43 UTC, jan-kiszka commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +	if (!strcmp(argv[1], "--help")) {
I think it's on the edge. ;)

2017-05-29 07:54 UTC, jan-kiszka commented
Updated switchmode according to feedback. I kept setledcolor on request by @SaschaWeisenberger, but I fixed it and install it now to the example image.

2017-05-30 13:23 UTC, stormc commented on meta-iot2000-example/recipes-tools/switchmode/files/switchmode.c
> +		return 1;
I'm not aware of a convention here but I'd like to be able to differentiate the two failure cases based on the exit code, e.g., in a script. As said, nitpicking... It's up to your taste.

2017-05-30 13:33 UTC, stormc requested changes

2017-05-30 13:33 UTC, stormc commented on meta-iot2000-example/recipes-tools/setledcolor/files/setledcolor.py
> +        file.close()
Well, this closes the file just when writing `0` to it. `file.close()` should be "de-indented".

2017-05-30 13:33 UTC, stormc commented on meta-iot2000-example/recipes-tools/setledcolor/files/setledcolor.py
> +    file = open(redLedFile, 'w')
This may fail with an exception and the failure isn't handled here. Probably not worth the effort for this example script?

2017-05-30 13:40 UTC, jan-kiszka commented on meta-iot2000-example/recipes-tools/setledcolor/files/setledcolor.py
> +        file.close()
Good catch, thanks.

2017-05-30 13:41 UTC, jan-kiszka commented on meta-iot2000-example/recipes-tools/setledcolor/files/setledcolor.py
> +    file = open(redLedFile, 'w')
Yes, but the most likely error - non-existing sysfs file - is caught above. OTH, one could avoid that check and handle the exception instead...

2017-05-31 06:20 UTC, stormc approved these changes

2017-05-31 19:47 UTC, merged