Add script to generate the license file
siemens/meta-iot2000 pull request #63
Opened 2017-11-16 06:26 UTC by johnson325

2017-11-20 13:39 UTC, jan-kiszka requested changes
Is scripts/*bin*/ a typical path here? I would just put it in .../scripts.

2017-11-20 13:39 UTC, jan-kiszka commented on meta-iot2000-example/scripts/bin/extract_license
> +#
Copyright and license header is missing. We didn't use that consistently so far, specifically leaving trivial one or two-line files untagged, but we should do better. Grab the pattern from meta-iot2000-bsp/recipes-tools/switchmode/files/switchmode.c e.g.

2017-11-20 13:39 UTC, jan-kiszka commented on meta-iot2000-example/scripts/bin/extract_license
> +    file_path=$dir/$file
Please indent this for loop block properly.

2017-11-20 13:39 UTC, jan-kiszka commented on meta-iot2000-example/scripts/bin/extract_license
> +
Unneeded newline

2017-11-21 06:26 UTC, jan-kiszka commented
Please fold your fixes into the the original commit (no need to merge review history). And don't forget to sign-off the commit.

2017-11-22 01:23 UTC, johnson325 commented
Done. Thanks for the comments.

2017-11-22 20:35 UTC, merged